# Generated by Django 4.0.2 on 2022-02-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indextext',
            options={'verbose_name': 'Тест главной страницы', 'verbose_name_plural': 'Тест главной страницы'},
        ),
    ]
