# Generated by Django 4.0.2 on 2022-02-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_indextext_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlider1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icon', verbose_name='Логотип')),
                ('img', models.ImageField(upload_to='img', verbose_name='Фото')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Что я должен делать',
            },
        ),
    ]
