# Generated by Django 4.0.2 on 2022-02-27 16:18

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_direction_alter_indexslider1_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='CategoryDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Наименование категории')),
            ],
            options={
                'verbose_name': 'Категории напровлении',
                'verbose_name_plural': 'Категории напровлении',
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='category',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='backend.categorydirection', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
