# Generated by Django 4.0.2 on 2022-03-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_aboutkg_blog_contacts_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
