# Generated by Django 4.0.2 on 2022-03-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_direction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='index',
            field=models.CharField(default=23, max_length=50, verbose_name='Почтовый индекс'),
            preserve_default=False,
        ),
    ]
