# Generated by Django 4.0.2 on 2022-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contact_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropAs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Фориа обратной связи',
                'verbose_name_plural': 'Фориа обратной связи',
            },
        ),
    ]
